globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Carnivoor Experiments / %s"
og_image: /img/og.png
author: Mauricio Wolff
favicon: /img/favicon.png
description: An ongoing experiment to understand the impact of a carnivore diet on health and well-being.

port: 8083

# OG image
origin: https://carnivoorexperiment.nl
og: /img/og.jpg

navigation:
  header:
    - Carnivoor Experiment: /
    - Contact: /contact

  footer:
    - © Mauricio Wolff: /

    - image: /img/icon-linkedin.svg
      url: //linkedin.com/in/mauriciowolff
      alt: LinkedIn profile
      size: 22 x 22

    - image: /img/icon-github.svg
      url: //github.com/bitbonsai/carnivoorexperiment.nl
      alt: Github Projects
      size: 22 x 22

    - image: /img/icon-website.svg
      url: //mauriciowolff.com
      alt: Author's personal website
      size: 22 x 22
